Exercise 3

Let's make the dataset?

In [1]:
import numpy as np
dataset = np.arange(1, 50).reshape(7, 7)

Now let's get to the exercises.

In [ ]:
# Task 1:
# Let's add 50 to all values in the dataset.
dataset1 = dataset + 50
print(dataset1)

[[51 52 53 54 55 56 57]
 [58 59 60 61 62 63 64]
 [65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78]
 [79 80 81 82 83 84 85]
 [86 87 88 89 90 91 92]
 [93 94 95 96 97 98 99]]


In [3]:
# Task 2:
# Let's sum all the values in the dataset.
dataset_sum = np.sum(dataset)
print(dataset_sum)

1225


In [ ]:
# Task 3:
# Let's sum only odd values in the dataset.
dataset_odd_sum = np.sum(dataset[dataset % 2 == 1])
print(dataset_odd_sum)


625


In [5]:
# Task 4:
# Let's use standard deviation of the dataset.
dataset_std = np.std(dataset)
print(dataset_std)

14.142135623730951


In [ ]:
# Task 5:
# Let's row-wise sum the dataset.
dataset_row_sum = np.sum(dataset, axis=1)
print(dataset_row_sum)


[ 28  77 126 175 224 273 322]


In [7]:
# Task 6:
# Let's column-wise sum the dataset.
dataset_col_sum = np.sum(dataset, axis = 0)
print(dataset_col_sum)

[154 161 168 175 182 189 196]
