Exercise 3

In [1]:
# Let's import numpy.
import numpy

Let's get to the exercises

In [ ]:
# Task 1:
# Let's create a NumPy vector (list)
# Containing these values: 5, 16, 9, 2, 19, 18, 11, 7.
vector = numpy.array([5, 16, 9, 2, 19, 18, 11, 7])
print("Original vector:", vector)


Original vector: [ 5 16  9  2 19 18 11  7]


In [3]:
# Task 2:
# Let's create a 7x7 array (matrix)
# With random integers between 0 and 49.
rng = numpy.random.default_rng()
data = rng.integers(0, 49, size = 49).reshape(7, 7)
print(data)

[[33 18 20 19  0  7  8]
 [22  7  7 24 11 17 12]
 [29  9 14 11  9 25 47]
 [ 4 41 44 29 19 31 45]
 [ 1 43  4 24 41 28  4]
 [37 10 42 44 25 24 47]
 [35 13 24 47 27 45 43]]


In [5]:
# Task 3:
# Let's generate 8x8 random number matrix
# Integer values between 0 and 5.
data = rng.integers(0, 6, size=64).reshape(8, 8)
print(data)

[[1 0 2 4 4 1 3 2]
 [2 0 0 1 4 3 3 2]
 [1 1 4 4 4 5 3 0]
 [0 3 3 0 1 5 4 1]
 [1 4 1 0 0 2 4 3]
 [2 2 3 0 0 4 2 0]
 [2 2 1 4 0 2 1 2]
 [2 3 0 5 1 5 3 3]]


In [6]:
# Task 4:
# Let's generate 8x8 random number matrix
# Using standard normal distribution values.
# (Values are any decimal values between -3 and 3).
data = rng.integers(-3, 3, size=64).reshape(8,8)
print(data)

[[ 2  2 -3  2 -2 -3 -2  2]
 [ 0  2  0 -3  1 -3 -3 -3]
 [-3  1 -2 -3 -3 -2  2  1]
 [ 1 -3 -1 -1  2  0 -3 -3]
 [-3 -2 -3  1 -1  2  1 -2]
 [ 2  1 -2  1  0  1  0 -3]
 [ 2  0  2  1  2  2 -3  0]
 [-2 -1 -3 -3 -3 -1  0  1]]
