Exercise 5


Let's import numpy

In [2]:
import numpy as np

Let's get to the exercises.


In [3]:
# Task 1:
# Let's recreate the first photo.
data = np.random.randint(0, 100, size=(3,5))
print(data) 

[[70 59 24 20 95]
 [18  6 48 54 43]
 [85 78 53 99 78]]


In [4]:
# Task 2:
# Let's recreate the second photo.
data = np.random.randint(0, 255, size=(8, 16))
print(data)

[[ 26  27 193 217 196 179  13  58   1 245  80  16  55  47 220 210]
 [ 31 106 189  20 120  56 177 197   0  96 210 192 168  32  51  42]
 [ 66 117 172 229 239 137 223 250 213 162 167 146 179  55 202  71]
 [ 20 191 136 120  14   2  54 148  29 166   0  40 194  41 176 239]
 [  7 159 152 233 146 111  22 163  22  21  94  13 188 213 192 220]
 [ 54 203 229 242 224 200 171  49 168  36  34 135  93  32 125  27]
 [ 12  90  41 175  54  89  12  28 123  82 198  66 140 219  87 201]
 [142 203 119 209  30  59  70  49 121  59 167  72 153 210 160  68]]


In [5]:
# Task 3:
# Let's recreate the third photo.
data = np.arange(0, 5, 0.05).reshape(10, 10)
print(data)

[[0.   0.05 0.1  0.15 0.2  0.25 0.3  0.35 0.4  0.45]
 [0.5  0.55 0.6  0.65 0.7  0.75 0.8  0.85 0.9  0.95]
 [1.   1.05 1.1  1.15 1.2  1.25 1.3  1.35 1.4  1.45]
 [1.5  1.55 1.6  1.65 1.7  1.75 1.8  1.85 1.9  1.95]
 [2.   2.05 2.1  2.15 2.2  2.25 2.3  2.35 2.4  2.45]
 [2.5  2.55 2.6  2.65 2.7  2.75 2.8  2.85 2.9  2.95]
 [3.   3.05 3.1  3.15 3.2  3.25 3.3  3.35 3.4  3.45]
 [3.5  3.55 3.6  3.65 3.7  3.75 3.8  3.85 3.9  3.95]
 [4.   4.05 4.1  4.15 4.2  4.25 4.3  4.35 4.4  4.45]
 [4.5  4.55 4.6  4.65 4.7  4.75 4.8  4.85 4.9  4.95]]
