Exercise 2

In [5]:
# Let's import numpy
import numpy as np

Let's get to the exercises


In [6]:
# Task 1:
# Let's use numpy to create a list that displays
# Fifteen zeroes.
data = np.zeros(15)
print(data)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
# Task 2:
# Let's use numpy to create a list that displays
# Fifteen one's.
data = np.ones(15)
print(data)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [8]:
# Task 3:
# Let's use numpy to create a list that displays fifteen sevens.
data = np.full(15, 7)
print(data)

[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]


In [10]:
# Task 4:
# Let's use numpy to create array of numbrs from 100 to 150.
data = np.arange(100,151)
print(data)

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150]


In [11]:
# Task 5:
# Let's use numpy to create array of numbers
# From 1900 to 2021.
data = np.arange(1900, 2022)
print(data)

[1900 1901 1902 1903 1904 1905 1906 1907 1908 1909 1910 1911 1912 1913
 1914 1915 1916 1917 1918 1919 1920 1921 1922 1923 1924 1925 1926 1927
 1928 1929 1930 1931 1932 1933 1934 1935 1936 1937 1938 1939 1940 1941
 1942 1943 1944 1945 1946 1947 1948 1949 1950 1951 1952 1953 1954 1955
 1956 1957 1958 1959 1960 1961 1962 1963 1964 1965 1966 1967 1968 1969
 1970 1971 1972 1973 1974 1975 1976 1977 1978 1979 1980 1981 1982 1983
 1984 1985 1986 1987 1988 1989 1990 1991 1992 1993 1994 1995 1996 1997
 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011
 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021]


In [12]:
# Task 6:
# Let's use numpy to create array of even numbers between 0 and 100.
data = np.arange(0, 101, 2)
print(data)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [13]:
# Task 7:
# Let's use numpy to create array of years that are divisbile by 4 between
# years 1952 and 2021.
data = np.arange(1952, 2021, 4)
print(data)

[1952 1956 1960 1964 1968 1972 1976 1980 1984 1988 1992 1996 2000 2004
 2008 2012 2016 2020]
